#!/usr/bin/env ruby
require 'optparse'
require 'pathname'

root_path = Pathname.new($0).realpath.dirname.to_s # path of executable run, resolving symbolic links


module Slackdown; end
class Slackdown::Cli
  VERSION = "1.0.0"
  def self.parse!

    args = Struct.new(:none).new

    opt_parser = OptionParser.new do |opts|
      opts.banner = <<~BANNER
      Usage: slackdown [options]

      Converts Github Flavored Markdown (GFM) to formatting slack understands.

      By default, input is taken from the system clipboard, converted, and
      pasted to the system clipboard.

      BANNER

      opts.on("-h", "--help", "Prints this help") do
        opts.summary_width = 20
        puts opts
        exit
      end

      opts.on("-v", "--version", "Prints the version (#{VERSION})") do
        puts VERSION
        exit
      end
    end

    opt_parser.parse!
    return args
  end
end

args = Slackdown::Cli.parse!

exec("pbpaste | pandoc -f gfm -t #{root_path}/lib/slack_doc.lua | pbcopy")
